# Generated by Django 5.2.17 on 2026-09-28 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Lead full name or business name', max_length=150)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=30)),
                ('email', models.EmailField(blank=True, help_text='Contact email address', max_length=254)),
                ('source', models.CharField(help_text='Acquisition channel (e.g. telegram, website, referral)', max_length=100)),
                ('note', models.TextField(blank=True, help_text='Notes and additional context about the lead')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('won', 'Won'), ('lost', 'Lost')], db_index=True, default='new', help_text='Current qualification status of the lead', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='CRM user responsible for managing this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='STATUS_CHANGE', max_length=50)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'source'], name='leads_lead_status_b280c3_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['-created_at'], name='leads_lead_created_921505_idx'),
        ),
    ]
